# CONSTANTS
PACKAGE_SIZE = 1024
POSITION_SIZE = 4
DATA_SIZE = PACKAGE_SIZE - POSITION_SIZE

# MARKERS
START_MARKER = b"//START//"
END_MARKER = b"//END//"
SENDER_ERROR_MARKER = b"//SENDER_ERROR//"

# FOR SENDER
TARGET_IP = "147.32.221.18"
TARGET_PORT = 5020

# ERROR MESSAGES
ERROR_PACKAGE_SIZE = "Error: package size is bigger than maximum package size"