# CONSTANTS
SENDING_WINDOW = 5
TYPE_SIZE = 1
PACKAGE_SIZE = 1024
CRC_SIZE = 4
POSITION_SIZE = 4
ID_SIZE = 4
DATA_SIZE = PACKAGE_SIZE - POSITION_SIZE - CRC_SIZE - ID_SIZE - TYPE_SIZE

TIMEOUT = 2
MAX_TRIES = 20

# POSITIONSS IN PACKAGE
CRC_POS = slice(0, CRC_SIZE)
TYPE_POS = slice(CRC_SIZE, CRC_SIZE + TYPE_SIZE)
ID_POS = slice(TYPE_SIZE + CRC_SIZE, TYPE_SIZE + CRC_SIZE + ID_SIZE)
POSITION_POS = slice(TYPE_SIZE + CRC_SIZE + ID_SIZE, TYPE_SIZE + CRC_SIZE + ID_SIZE + POSITION_SIZE)
DATA_POS = slice(TYPE_SIZE + CRC_SIZE + POSITION_SIZE + ID_SIZE, PACKAGE_SIZE)

# PACKAGE TYPES
INFO_TYPE = b"I"
MARKER_TYPE = b"M"
HASH_TYPE = b"H"
DATA_TYPE = b"D"

# MARKERS
START_MARKER = b"//START//"
END_MARKER = b"//END//"
ACKNOWLEDGE_MARKER = b"//ACK//"
DENIED_MARKER = b"//DENIED//"
SENDER_ERROR_MARKER = b"//SENDER_ERROR//"

# FOR SENDER
SENDER_IP = "192.168.165.115"
SENDER_PORT = 5002
SENDER_ADRESS = (SENDER_IP, SENDER_PORT)

# FOR RECEIVER
TARGET_IP = "147.32.221.18"
TARGET_PORT = 5020
TARGET_ADRESS = (TARGET_IP, TARGET_PORT)


# ERROR MESSAGES
ERROR_PACKAGE_SIZE = b"Error: package size is bigger than maximum package size"
ERROR_START_MARKER = b"Error: start marker is not correct"
ERROR_SENDER_ERROR = b"Error: sender had an error"
ERROR_MAX_TRIES = b"Error: maximum tries to recieve acknowledge reached"
